spring:
  application:
    name: spring-data-demo-1
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/cs545
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

server:
  port: 8080
