spring:
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: 'create'
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/springdatai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    jpa:
      repositories:
        enabled: true
hibernate:
  dialect:
    org:
      hibernate:
        dialect: MySQL5Dialect
