spring:
  application:
    name: spring-data-demo-1
  datasource:
    password: O1933419@mssqlserver
    url: jdbc:sqlserver://localhost;databaseName=Lab03;encrypt=false;
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 8080