#For POSTGRES CONNECTIONS

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5433/WAA
    username: postgres
    password: root12345
    driverClassName: org.postgresql.Driver


# FOR MYSQL CONNECTIONS
#spring:
#  datasource:
##    url: jdbc:mysql://localhost:3306/waa?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#    url: jdbc:postgresql://localhost:5432/waa
#    username: postgres
#    password: 12345678
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#
#
##server:
##  port: 8083
#
#
